christ/christ/urls.py
from django.contrib import admin
from django.urls import path,include
from knowledgepro import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('knowledgepro/',include('knowledgepro.urls')),
    path('logout/',views.user_logout,name='logout'),


]

christ/knowledgepro/urls.py
from django.urls import path

from knowledgepro import views

app_name = 'knowledgepro'
urlpatterns=[

        path('register',views.register,name='register'),
        path('user_login/',views.user_login,name='user_login')
]

christ/knowledgepro/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    display_pic = models.ImageField(upload_to = 'display_pictures',blank= True)
    linkedIn_url =  models.URLField(blank=True)

    def __str__(self):
        return self.user.username 

christ/knowledgepro/forms.py
from django.contrib.auth.models import User
from django import forms
from knowledgepro.models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')


class UserDetailsForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('display_pic','linkedIn_url')
        

christ/knowledgepro/views.py
from django.shortcuts import render
from knowledgepro.forms import UserDetailsForm,UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate
# Create your views here.

def home(request):
    return render(request,'knowledgepro/home.html')
def register(request):

    registered =  False
    if request.method =='POST':

        user_form = UserForm(request.POST)
        details_form = UserDetailsForm(request.POST)

        if user_form.is_valid() and details_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            details = details_form.save(commit=False)
            details.user = user
            if 'display_pic' in request.FILES:
                details.display_pic = request.FILES['display_pic']
            details.save()

            registered = True
        else:
            print(user_form.errors,details_form.errors)
    else:
        user_form = UserForm()
        details_form = UserDetailsForm()

    return render(request,'knowledgepro/register.html',{'user_form':user_form,'registered':registered,'details_form':details_form})


def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)

                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("in active account")
        else:
            return HttpResponse('<h1>Invalid Login Credentials</h1>')
    else:
        return render(request,'knowledgepro/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

christ/templates/knowledgepro/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-static-top">
  <a class="navbar-brand" href="{% url 'home' %}">Christ University</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">

  </button>

    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'knowledgepro:register' %}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'knowledgepro:user_login' %}">Login</a>
        </li>

      {% endif %}

    </ul>

</nav>


<div class="container">

  {% block body_block %}

  {% endblock %}

</div>

  </body>
</html>

christ/templates/knowledgepro/home.html
{% extends 'knowledgepro/base.html' %}

{% block body_block %}

<div class="jumbotron">
  <h1>Welcome to Christ University</h1>
<a class="btn btn-primary btn-lg" href="{% url 'knowledgepro:register' %}" role="button">Sign up now</a>
</div>

{% endblock %}

christ/templates/knowledgepro/login.html
{% extends 'knowledgepro/base.html' %}

{% block body_block %}

<div class="jumbotron">
  <h1>knowledge pro Login</h1>

  <div class="jumbotron">

    <form action="{% url 'knowledgepro:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username</label>
      <input type="text" name="username" value="">
<label for="password">Password</label>
<input type="text" name="password" value="">
<input type="submit" name="" value="Login">
    </form>

  </div>
</div>

{% endblock %}

christ/templates/knowledgepro/register.html
{% extends 'knowledgepro/base.html' %}
{% load static %}

{% block body_block %}

<div class="container">
  <h1>Christite Registration</h1>

    {% if registered %}
      <h1>Dear Christite, <br> you have successfully registered to our site! :)</h1>


    {% else %}
      <div class="jumbotron">

          <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{user_form.as_p}}
            {{details_form.as_p}}
            <input type="submit" name="" value="sign up">

          </form>

        </div>
    {% endif %}
</div>


{% endblock %}